# Add labels to pull requests based on file changes

documentation:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
      - 'docs/**'

dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.npmrc'

source-code:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/**/*.ts'
      - 'src/**/*.js'

tests:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.test.ts'
      - '**/*.spec.ts'
      - 'test/**'
      - 'tests/**'

ci:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/workflows/**'
      - '.github/actions/**'

config:
  - changed-files:
    - any-glob-to-any-file:
      - 'tsconfig.json'
      - '.eslintrc.*'
      - '.prettierrc.*'
      - '.*ignore'